### PR TITLE
issue #5 Options to Emit Errors to the Stream

### LINKED ISSUE #5: How to make browserify fail/error coffeelint errors
I need the browserify stream to emit errors; currently I do not see any errors reported back to browserify and it is only pumped out to reporter.

https://github.com/nolemmings/browserify-coffeelint/blob/master/index.coffee#L18

This is useful for making pipelines fail like gulp and browserify.

### PR DESCRIPTION
**Pull request by nmccready**
adding error and warning emits if options ask for it

Resolves #5

### CODE REVIEW

File: index.coffee [hunk 1]
```diff
@@ -17,6 +17,12 @@ module.exports = (file, overrideOptions = {}) ->
       if errors.length isnt 0
         coffeelint.reporter file, errors
 
+        if options.doEmitErrors and errorReport.hasError()
+          next new Error ("coffeelint has errors")
+
+        if options.doEmitWarnings and _.any(errorReport.paths, (p) -> pathHasWarning p)
```
Comment (nmccready) [inline index.coffee]: Crap bug here should be `errorReport. pathHasWarning p`

Will fix.

**Comment by nmccready** [comment]
@nolemmings please review ty
